### PR TITLE
Coffeescript and backbone functional

### PR DESCRIPTION
**Pull request by ConorBrady**

### CODE REVIEW

**Comment by kevinbluett** [comment]
Can one of the admins verify this patch?

**Comment by ConorBrady** [comment]
Is that an automated comment?

**Comment by ConorBrady** [comment]
I imagine I've done some things against convention, so now would be a good time to point those out.

**Comment by kevinbluett** [comment]
testpr

**Comment by kevinbluett** [comment]
testpr

**Comment by kevinbluett** [comment]
testpr

**Comment by kevinbluett** [comment]
:bowtie:

**Pull request merged**
